#Wcs_wild_resa_homepage:
#   path:     /hello/{name}
#   defaults: { _controller: WcsWildResaBundle:Default:index }
#

wcs_wild_resa_homepage:
    path:     /
    defaults: { _controller: WcsWildResaBundle:Calendar:index }
