wcs_users:
    resource: "@WcsUsersBundle/Resources/config/routing.yml"
    prefix:   /

wcs_wild_resa:
    resource: "@WcsWildResaBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"