# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    sonata.Wild.Machines:
            class: Wcs\WildResaBundle\Admin\MachinesWild
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Liste des Machines", label: "Machine" }
            arguments:
                - ~
                - Wcs\WildResaBundle\Entity\Machines
                - ~

    wcs.wildresabundle.calendar_listener:
        class: Wcs\WildResaBundle\EventListener\CalendarEventListener
        arguments:
            _type: service
            _id: "doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_listener", event: "wcs.wildresabundle.calendar.load_events", method: loadEvents, id: "wcs.wildresabundle.calendar_listener" }