# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    sonata.Wild.Machines:
        class: Wcs\WildResaBundle\Admin\MachinesWild
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Machines", label: "Machines" }
        arguments:
            - ~
            - Wcs\WildResaBundle\Entity\Machines
            - ~

    sonata.Wild.Events:
        class: Wcs\WildResaBundle\Admin\EventsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Events", label: "Events" }
        arguments:
            - ~
            - Wcs\WildResaBundle\Entity\Events
            - ~

    sonata.user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileType
        arguments: [ "Application\Sonata\UserBundle\Entity\User" ]
        tags:
            - { name: "form.type", alias: "application_sonata_user_profile"}

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }