events:
    path:     /
    defaults: { _controller: "WcsWildResaBundle:Events:index" }
    methods:  POST


events_show:
    path:     /{id}/show
    defaults: { _controller: "WcsWildResaBundle:Events:show" }
    methods:  POST


events_new:
    path:     /{start}/new
    defaults: { _controller: "WcsWildResaBundle:Events:new" }
    methods:  POST

events_create:
    path:     /create
    defaults: { _controller: "WcsWildResaBundle:Events:create" }
    methods:  POST

events_edit:
    path:     /{id}/edit
    defaults: { _controller: "WcsWildResaBundle:Events:edit" }
    methods:  POST


events_update:
    path:     /{id}/update
    defaults: { _controller: "WcsWildResaBundle:Events:update" }
    methods:  [POST, PUT]

events_delete:
    path:     /{id}/delete
    defaults: { _controller: "WcsWildResaBundle:Events:delete" }
    methods:  [POST, DELETE]
