evententity:
    path:     /
    defaults: { _controller: "WcsWildResaBundle:EventEntity:index" }

evententity_show:
    path:     /{id}/show
    defaults: { _controller: "WcsWildResaBundle:EventEntity:show" }

evententity_new:
    path:     /new
    defaults: { _controller: "WcsWildResaBundle:EventEntity:new" }

evententity_create:
    path:     /create
    defaults: { _controller: "WcsWildResaBundle:EventEntity:create" }
    methods:  POST

evententity_edit:
    path:     /{id}/edit
    defaults: { _controller: "WcsWildResaBundle:EventEntity:edit" }

evententity_update:
    path:     /{id}/update
    defaults: { _controller: "WcsWildResaBundle:EventEntity:update" }
    methods:  [POST, PUT]

evententity_delete:
    path:     /{id}/delete
    defaults: { _controller: "WcsWildResaBundle:EventEntity:delete" }
    methods:  [POST, DELETE]
