Wcs\WildResaBundle\Entity\Events:
    type: entity
    manyToOne:
        machines:
            targetEntity: Wcs\WildResaBundle\Entity\Machines
            inversedBy: events
            joinColumn:
                name: type_machine
                referencedColumnName: id
    table: null
    repositoryClass: Wcs\WildResaBundle\Entity\EventsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: datetime
        end:
            type: datetime
    lifecycleCallbacks: {  }
