Wcs\WildResaBundle\Entity\Events:
    type: entity
    table: null
    repositoryClass: Wcs\WildResaBundle\Entity\EventsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        event_datetime:
            type: datetime
            column: event_datetime
        startDate:
            type: datetime
        endDate:
            type: datetime
    lifecycleCallbacks: {  }
