Wcs\WildResaBundle\Entity\Events:
    type: entity
    manyToMany:
        machines:
            targetEntity: Machines
            inversedBy: events
            joinTable:
                name: event_machine
                joinColumns:
                    events_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    machines_id:
                        referencedColumnName: id
    table: null
    repositoryClass: Wcs\WildResaBundle\Entity\EventsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: datetime
        end:
            type: datetime
        user:
            type: string
    lifecycleCallbacks: {  }
